### ISSUE TITLE
Magic String Problem: page not found

### ISSUE THREAD

**Issue by alaztetik** [jeantimex/javascript-problems-and-solutions#341]
The **Magic String** problem link with the the url of https://github.com/jeantimex/javascript-problems-and-solutions/blob/master/src/string/magic-string.js does not open, giving 404 error.

**Comment by EslamHiko** [comment]
@alaztetik I think you mean this : https://github.com/jeantimex/javascript-problems-and-solutions/blob/master/src/string/magical-string.js
